name: CI

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.7

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Dependencies
        run:  pip3 install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Code Quality
        run:  flake8 --max-line-length=120 setup.py gixy
